/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.classReportes;
import clases.control_cliente;
import herramientas.Reportes;
import herramientas.globales;
import static herramientas.globales.llenarComboGlobal;
import static interfaces.frmPrincipal.jDesktopPane1;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JTextField;

/**
 *
 * @author julio
 */

public class frmConsultaReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConsultaReportes
     */
    
    public frmConsultaReportes() {
        initComponents();
        //strQuery="SELECT idReporte,Descripcion from Reportes ";
        llenarComboGlobal(this.cboReporte,globales.gstrQuery,false);
        this.tabFechas.setVisible(false);
        this.tabCliente.setVisible(false);
        Calendar c2 = new GregorianCalendar();
        dteFecha.setCalendar(c2);
        dteFecha1.setCalendar(c2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboReporte = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bntImprimir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tabFechas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panRangoFechas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dteFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dteFecha1 = new com.toedter.calendar.JDateChooser();
        tabCliente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JTextField();
        lblNomCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboReporteActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte:");

        bntImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panRangoFechas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panRangoFechas.setToolTipText("");

        jLabel2.setText("DESDE:");

        dteFecha.setToolTipText("");
        dteFecha.setDateFormatString("yyyy-MM-dd");

        jLabel3.setText("HASTA:");

        dteFecha1.setToolTipText("");
        dteFecha1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout panRangoFechasLayout = new javax.swing.GroupLayout(panRangoFechas);
        panRangoFechas.setLayout(panRangoFechasLayout);
        panRangoFechasLayout.setHorizontalGroup(
            panRangoFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRangoFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panRangoFechasLayout.setVerticalGroup(
            panRangoFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRangoFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRangoFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dteFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panRangoFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panRangoFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabFechas.addTab("Fechas", jPanel1);

        panCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panCliente.setToolTipText("");

        jLabel4.setText("CLIENTE:");

        txtNumCliente.setText("0");
        txtNumCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumClienteActionPerformed(evt);
            }
        });
        txtNumCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumClienteEnterCliente(evt);
            }
        });

        lblNomCliente.setText("nombre");

        javax.swing.GroupLayout panClienteLayout = new javax.swing.GroupLayout(panCliente);
        panCliente.setLayout(panClienteLayout);
        panClienteLayout.setHorizontalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panClienteLayout.setVerticalGroup(
            panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomCliente))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabCliente.addTab("Cliente", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabFechas))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bntImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCliente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabFechas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntImprimir)
                    .addComponent(jButton1))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        classReportes reportes = new classReportes();
        String strConsulta="";
        
        reportes.leerReporte(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString());
        
        if (Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==3){
            
            strConsulta="select b.Fecha \n" +
                "		, sum(a.Importe_Neto) as IMPORTE_NETO \n" +
                "        , sum(a.Cantidad) as CANTIDAD \n" +
                "        , a.Descripcion \n" +
                "        , ('Desde "+((JTextField)this.dteFecha.getDateEditor().getUiComponent()).getText()+ " Hasta "+((JTextField)this.dteFecha1.getDateEditor().getUiComponent()).getText()+ "') as rango \n" +
                "        , (SELECT Logo FROM datosempresa) as logo \n" +
                "from ventasproductos a \n" +
                "        ,ventas b \n" +
                " where a.idPuntoVenta=b.PuntoVenta \n" +
                "     and a.idVenta=b.idVenta \n" +
                "     and b.Fecha BETWEEN '"+((JTextField)this.dteFecha.getDateEditor().getUiComponent()).getText()+ "' and '"+((JTextField)this.dteFecha1.getDateEditor().getUiComponent()).getText()+ "' \n" +
                " group by a.Descripcion";
            Reportes.lanzarReporte(strConsulta, reportes.strNombreReporte);
            return ;
        }
        
         if (Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==4){
            
            strConsulta="SELECT b.Descripcion\n" +
                        "       ,sum(b.Cantidad) as Cantidad\n" +
                        "       ,sum(b.Cantidad*b.Precio) as Importe\n" +
                        "       ,(SELECT Logo FROM datosempresa) as logo\n" +
                        "       , ('Desde "+((JTextField)this.dteFecha.getDateEditor().getUiComponent()).getText()+ " Hasta "+((JTextField)this.dteFecha1.getDateEditor().getUiComponent()).getText()+ "') as rango \n" +
                        "FROM movimientoinventario a\n" +
                        "    ,inventarioProductos b\n" +
                        "where a.EntradaSalida=b.EntradaSalida\n" +
                        "    and a.idTipoFlujo=b.idTipoFlujo\n" +
                        "    and a.idBodega=b.idBodega\n" +
                        "    and a.idFolio=b.idFolio\n" +
                        "    and a.Fecha BETWEEN '"+((JTextField)this.dteFecha.getDateEditor().getUiComponent()).getText()+ "' and '"+((JTextField)this.dteFecha1.getDateEditor().getUiComponent()).getText()+ "' \n" +
                        "    and a.EntradaSalida='Entrada'\n" +
                        "group by b.Producto,b.Descripcion";
            Reportes.lanzarReporte(strConsulta, reportes.strNombreReporte);
            return ;
        }
         
         if (Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==5){
            
            strConsulta="SELECT b.idCartera\n" +
                        "       ,b.Fecha\n" +
                        "        ,(SELECT a.Nombres   from Clientes a where 	a.idCliente=b.idCliente) as CLIENTE\n" +
                        "        ,b.Observaciones\n" +
                        "        ,b.Importe\n" +
                        "        ,b.CargoAbono\n" +
                        "        ,b.idCliente\n" +
                        "	,(SELECT Logo FROM datosempresa) as logo\n" +
                        "FROM cartera b\n" +
                        "WHERE b.idCliente="+frmConsultaReportes.txtNumCliente.getText();
            
            Reportes.lanzarReporte(strConsulta, reportes.strNombreReporte);
            return ;
        }
        Reportes.lanzarReporte(reportes.strConsulta, reportes.strNombreReporte);
    }//GEN-LAST:event_bntImprimirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboReporteActionPerformed
        if(Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==3){
            this.panRangoFechas.setVisible(true);
            this.tabFechas.setVisible(true);
        }
        
         if(Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==4){
            this.panRangoFechas.setVisible(true);
            this.tabFechas.setVisible(true);
        }
         
         if(Long.valueOf(this.cboReporte.getSelectedItem().toString().substring(0, 4).toString())==5){
            this.panCliente.setVisible(true);
            this.tabCliente.setVisible(true);
        }
    }//GEN-LAST:event_cboReporteActionPerformed

    private void txtNumClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumClienteActionPerformed

    private void txtNumClienteEnterCliente(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumClienteEnterCliente
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            control_cliente cliente = new control_cliente();
            cliente.leerCliente(this.txtNumCliente.getText());
            this.lblNomCliente.setText(cliente.strNombre+" " +cliente.strApellido);
            
        }

        if(evt.getKeyCode() == KeyEvent.VK_F3) {
            frmBuscarPersonaReporte buscarPersona = new frmBuscarPersonaReporte();
            jDesktopPane1.add(buscarPersona);
            buscarPersona.show();
        }
    }//GEN-LAST:event_txtNumClienteEnterCliente

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntImprimir;
    private javax.swing.JComboBox<String> cboReporte;
    private com.toedter.calendar.JDateChooser dteFecha;
    private com.toedter.calendar.JDateChooser dteFecha1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblNomCliente;
    private javax.swing.JPanel panCliente;
    private javax.swing.JPanel panRangoFechas;
    private javax.swing.JTabbedPane tabCliente;
    private javax.swing.JTabbedPane tabFechas;
    public static javax.swing.JTextField txtNumCliente;
    // End of variables declaration//GEN-END:variables
}
